### ISSUE TITLE
戒指离线时是否能开启触控录音功能？

### ISSUE THREAD

**Issue by sword-zhi** [Z-y-hu/ChipletRing-SDK-Android#10]
1.戒指离线时是否能开启触控录音功能？经过调试后发现app在后台时能正常开始触控录音功能，但app被强制关闭（断开戒指连接）后触控录音无法使用，看能否处理这个需求
2.戒指录音现在的版本无法接收到pcm数据，demo里提供的是处理adpcm数据的方法，但对应的.so库暂时无法在我们的项目中使用，是否有办法用其它方法处理adpcm数据或接收旧的pcm数据并处理

**Comment by sword-zhi** [comment]
关于第二个问题，.so文件可通过System.loadLibrary("ambientlight")正常导入，但在调用adpcmToPcmFromJNI方法时报以下错误，
No implementation found for byte[] expo.modules.chipletringdevicemanager.ExpoChipletRingDeviceManagerModule.adpcmToPcmFromJNI(byte[]) (tried Java_expo_modules_chipletringdevicemanager_ExpoChipletRingDeviceManagerModule_adpcmToPcmFromJNI and Java_expo_modules_chipletringdevicemanager_ExpoChipletRingDeviceManagerModule_adpcmToPcmFromJNI___3B)

**Comment by Z-y-hu** [comment]
1.目前不支持戒指离线录音，离线录音涉及录音数据的存储和读取，需讨论定制   
2.so文件的导入已放到aar当中，demo有示例可以直接使用
