### ISSUE TITLE
关掉混淆后编译时的错误

### ISSUE THREAD

**Issue by leeli46** [Z-y-hu/ChipletRing-SDK-Android#4]
会报一个这个问题
![image](https://github.com/user-attachments/assets/b1319ac5-3843-4d08-afdf-b6e789510e52)

**Comment by Z-y-hu** [comment]
这个权限被拒绝了的问题我从没遇到过，SDK里没有用到“vendor.debug.trace.perf”     
![4fbe9218f1b097d8e8c3a1767211362](https://github.com/user-attachments/assets/92b712be-8c92-44f4-a1bc-4abfbaecab9d)     
考虑下是你的项目中哪里用到了，不需要的话可以删掉

**Comment by leeli46** [comment]
图错了，是这张
![image](https://github.com/user-attachments/assets/83f436af-fcb3-41c9-bc2f-737f5b76017e)
好像也是greenDAO导致的

**Comment by Z-y-hu** [comment]
引入greenDAO依赖后解决该问题
