### ISSUE TITLE
新demo存在问题

### ISSUE THREAD

**Issue by leeli46** [Z-y-hu/ChipletRing-SDK-Android#6]
demo更新后有报错，
![image](https://github.com/user-attachments/assets/8c751af7-4d3e-4b11-b812-c33eb8e390ef)

**Comment by Z-y-hu** [comment]
这是刚刚上传的demo截图
![9c0646d81127619d4845f49a1d65a98](https://github.com/user-attachments/assets/ed45fc48-97ac-4365-8f0d-bebc742480b9)
这里不应该有问题，看下问题详情是什么

**Comment by leeli46** [comment]
![image](https://github.com/user-attachments/assets/9c5e6f78-7476-4144-9dae-06bcd59da48f)
是这样子的，原先的demo和这个而不太一样

**Comment by leeli46** [comment]
![image](https://github.com/user-attachments/assets/757c5b62-8930-4ff8-b5d9-d17c45bd3e50)

**Comment by Z-y-hu** [comment]
重新Sync 一下gradle就行了
