### ISSUE TITLE
SDK更新后编译失败

### ISSUE THREAD

**Issue by sword-zhi** [Z-y-hu/ChipletRing-SDK-Android#8]
1.从sdk1.0.18更新到1.0.19后编译提示java.lang.RuntimeException: Duplicate class a.a found in modules ChipletRing1.0.19.aar -> jetified-ChipletRing1.0.19-runtime (ChipletRing1.0.19.aar) and android-smartband-sdk-sxrblejy2library-release.aar -> jetified-android-smartband-sdk-sxrblejy2library-release-runtime (android-smartband-sdk-sxrblejy2library-release.aar)
2.现在的音频数据byte[]有没有现成方法能直接存储到文件，没有的话麻烦提供一下"采样率，声道数，位深" 这三个数据
3.戒指的过滤可以直接通过前缀BCL过滤么，demo是没有过滤方法的

**Comment by sword-zhi** [comment]
确认了一下ChipletRing1.0.19.aar跟我这边另一个戒指项目的android-smartband-sdk-sxrblejy2library-release.aar包冲突，冲突位置如上所述，现已回退到ChipletRing1.0.18.aar版本，麻烦帮忙看下剩下两个问题

**Comment by hzjsftw** [comment]
2. public static void convertByteToPcm(byte[] bytes, String filePath) throws IOException {
        File file = new File(filePath);
        try (BufferedSink sink = Okio.buffer(Okio.sink(file,true))) {
            sink.write(bytes);
        } catch (IOException e) {
            e.printStackTrace();
        }
filePath是需要创建的pcm文件路径
在public void CONTROL_AUDIO(byte[] bytes) 里调用。
如果需要播放，可以使用AudioTrack，
 /**
采样率等参数
**/
  int sampleRateInHz = 8000; // 采样率
    int channelConfig = AudioFormat.CHANNEL_OUT_MONO; // 声道配置
    int audioFormat = AudioFormat.ENCODING_PCM_16BIT; // 音频格式

  bufferSizeInBytes = AudioTrack.getMinBufferSize(sampleRateInHz, channelConfig, audioFormat); // 缓冲区大小

        /**
         * 设置音频信息属性
         * 1.设置支持多媒体属性，比如audio，video
         * 2.设置音频格式，比如 music
         */
        AudioAttributes attributes = new AudioAttributes.Builder()
                .setUsage(AudioAttributes.USAGE_MEDIA)
                .setContentType(AudioAttributes.CONTENT_TYPE_MUSIC)
                .build();
        /**
         * 设置音频格式
         * 1. 设置采样率
         * 2. 设置采样位数
         * 3. 设置声道
         */
        AudioFormat format = new AudioFormat.Builder()
                .setSampleRate(sampleRateInHz)
                .setEncoding(AudioFormat.ENCODING_PCM_16BIT)
                .setChannelMask(channelConfig)
                .build();
        audioTrack = new AudioTrack(attributes,format,bufferSizeInBytes,AudioTrack.MODE_STREAM, AudioManager.AUDIO_SESSION_ID_GENERATE);


3.过滤可以在搜索的时候，自己根据前缀来过滤是否显示
private BluetoothAdapter.LeScanCallback leScanCallback = new BluetoothAdapter.LeScanCallback() {
可以得到device.getName()

**Comment by sword-zhi** [comment]
我这边用的是short[]还没改成byte[]的旧的1.0.18包才能正常运行，我用你们提供的音频采样率自行转换一下，后面更新的1.0.18和1.0.19都会冲突，还是麻烦抽空看一下能不能解决，不然以后出新版SDK也一样会冲突

**Comment by sword-zhi** [comment]
Duplicate class a.a found in modules ChipletRing1.0.21.aar -> jetified-ChipletRing1.0.21-runtime (ChipletRing1.0.21.aar) and android-smartband-sdk-sxrblejy2library-release.aar -> jetified-android-smartband-sdk-sxrblejy2library-release-runtime (android-smartband-sdk-sxrblejy2library-release.aar)
今天更新的ChipletRing1.0.21.aar还是会出现冲突，我这边没办法手动处理aar文件里的冲突项，暂时只能用ChipletRing1.0.17.aar及之前的版本才可正常编译

**Comment by Z-y-hu** [comment]
aar已经更新了，最新的1.0.22应该解决了这个问题

**Comment by Z-y-hu** [comment]
最终取消混淆，自1.0.22版本之后都没问题了
