### ISSUE TITLE
触摸录音后没有音频返回

### ISSUE THREAD

**Issue by pangxiezhou** [Z-y-hu/ChipletRing-SDK-Android#9]
[phone_log.txt](https://github.com/user-attachments/files/18178276/phone_log.txt)

Uploading tmp8gaeyn65.mp4…

触摸按下后看到控制台有SDK的数据打印，但是Demo中没有对应callback

**Comment by pangxiezhou** [comment]
https://github.com/user-attachments/assets/e8d1950f-b985-4171-afea-d9ee476503dd

**Comment by Z-y-hu** [comment]
1.0.23已补充设置录音类型的接口，设置为adpcm   

![691553e7246a6f8cdcbd9f856cf180b](https://github.com/user-attachments/assets/f54a7895-50c4-4a9d-b1e2-197189a5f2f5)

**Comment by Z-y-hu** [comment]
已支持adpcm的触摸长按录音，松开结束录音和指令发送开始和结束来录音
